name: Frontend Deployment

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/client.yml"

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "client/pnpm-lock.yaml"

      - name: Install Dependencies
        run: |
          cd client
          pnpm install --frozen-lockfile

      - name: Build Project
        run: |
          cd client
          pnpm run build

      - name: Install Vercel CLI
        run: pnpm install -g vercel@latest

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          cd client
          vercel deploy --prod --token=${VERCEL_TOKEN} --yes

      - name: Notify Deployment
        run: |
          echo "Deployment triggered successfully."
          echo "You can check the status on Vercel dashboard."
