name: Deploy Backend to Server

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/server.yml"

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "server/pnpm-lock.yaml"

      - name: Install Dependencies
        run: |
          cd server
          pnpm install --frozen-lockfile

      - name: Run Tests
        run: |
          cd server
          pnpm run test || true

      - name: Build Project
        run: |
          cd server
          pnpm run build

      - name: Deploy to Server
        env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          # Trigger a deployment on Render
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json"

      - name: Notify Deployment
        run: |
          echo "Deployment triggered successfully."
          echo "You can check the status on Render dashboard. Visit https://dashboard.render.com to view your service."
